# Generated by Django 4.2.10 on 2024-11-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('stdId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stdName', models.CharField(max_length=50)),
                ('stdYear', models.IntegerField()),
                ('stdCourse', models.CharField(max_length=5)),
            ],
        ),
    ]
